I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script
    init python:
  File "game/script.rpy", line 50, in script
    init python:
  File "game/script.rpy", line 52, in <module>
    if show_mc_side_image == False:
NameError: name 'show_mc_side_image' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/mellnguyen/Desktop/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/Users/mellnguyen/Desktop/renpy-7.4.11-sdk/renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 50, in script
    init python:
  File "game/script.rpy", line 50, in script
    init python:
  File "/Users/mellnguyen/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/mellnguyen/Desktop/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 52, in <module>
    if show_mc_side_image == False:
NameError: name 'show_mc_side_image' is not defined

Darwin-21.5.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Diffraction 1.0
Sun Jun 12 16:44:07 2022
